export const REQUEST_NEXT_DATA = 'REQUEST_NEXT_DATA';
export const REQUEST_ANOTHER_DATA = 'REQUEST_ANOTHER_DATA';
export const RECEIVE_DATA = 'RECEIVE_DATA';
export const RECEIVE_FAIL = 'RECEIVE_FAIL';